twitter-to-kafka-service:
  twitter-keywords:
    -java
    -Microservice
    -Spring
    -Kafka
    -ElastcSearch
  welcome-message: Hello-microservices
  enable-mock-tweets: true
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 10000